ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'PENDING_REPLY';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TABLE "Appointment" ADD COLUMN "durationMinutes" INTEGER, ADD COLUMN "price" DECIMAL(65,30);
ALTER TABLE "Student" ADD COLUMN "requiredDocuments" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "receivedDocuments" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "collegeService" TEXT NOT NULL DEFAULT 'CONSULTATION';
ALTER TABLE "Event" ADD COLUMN "capacity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "EventLead" ADD COLUMN "partySize" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "CollegeCourse" ADD COLUMN "coordinatorId" TEXT;
