import { NextResponse } from 'next/server';
import { hash } from 'bcryptjs';
import { randomInt } from 'crypto';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { sendWhatsApp } from '@/lib/notifications';
import { securityRateLimit } from '@/lib/security';
const schema=z.object({phone:z.string().min(8).max(25)});
const normalize=(phone:string)=>phone.replace(/[^0-9]/g,'');
export async function POST(request:Request){const parsed=schema.safeParse(await request.json().catch(() => null));if(!parsed.success)return NextResponse.json({error:'Enter a valid phone number'},{status:400});const phone=normalize(parsed.data.phone);if(phone.length<8||phone.length>15)return NextResponse.json({error:'Enter a valid phone number'},{status:400});const limit=await securityRateLimit({request,action:'BOOKING_CODE_REQUEST',identity:'otp',windowMs:15*60*1000,maximum:10});if(!limit.allowed)return NextResponse.json({error:'Too many code requests. Try again later.'},{status:429,headers:{'Retry-After':String(limit.retryAfter)}});const phoneLimit=await securityRateLimit({request,action:'BOOKING_CODE_PHONE',identity:phone,windowMs:60*60*1000,maximum:5,bindToIp:false});if(!phoneLimit.allowed)return NextResponse.json({error:'Too many codes requested for this phone. Try again later.'},{status:429,headers:{'Retry-After':String(phoneLimit.retryAfter)}});const latest=await prisma.bookingVerification.findFirst({where:{phone},orderBy:{createdAt:'desc'}});if(latest&&Date.now()-latest.createdAt.getTime()<60000)return NextResponse.json({error:'Wait one minute before requesting another code'},{status:429});const code=String(randomInt(100000,1000000));const verification=await prisma.bookingVerification.create({data:{phone,codeHash:await hash(code,10),expiresAt:new Date(Date.now()+10*60000)}});const delivery=await sendWhatsApp(`verification:${verification.id}`,phone,'BOOKING_VERIFICATION',process.env.WHATSAPP_BOOKING_CODE_TEMPLATE||'booking_verification_code',[code]);const developmentCode=process.env.NODE_ENV!=='production'&&process.env.BOOKING_DEV_OTP==='true';if(delivery.status!=='SENT'&&!developmentCode){await prisma.bookingVerification.update({where:{id:verification.id},data:{expiresAt:new Date(0)}});return NextResponse.json({error:'Unable to send the verification code. Please try again later.'},{status:503});}return NextResponse.json({ok:true,expiresIn:600,...(process.env.NODE_ENV!=='production'&&process.env.BOOKING_DEV_OTP==='true'?{devCode:code}:{})});}
