'use client';
import {useEffect,useState} from 'react';
import {actorDepartments,financial,type Actor} from '@/lib/crm-access';
import {label} from '@/lib/crm-config';
export default function CrmDocumentUpload({user,onUpload,disabled,invoices=[]}:{user:Actor;onUpload:(file:File,category:string,department:string,invoiceId:string)=>Promise<void>;disabled:boolean;invoices:Record<string,any>[]}){
 const [invoiceId,setInvoiceId]=useState('');
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[category,setCategory]=useState('DOCUMENT'),[department,setDepartment]=useState(actorDepartments(user)[0]);
 useEffect(()=>{if(!file?.type.startsWith('image/')){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 return <section className="crm-panel"><h3>صورة أو مستند — حتى 4 MB</h3><div className="crm-form-grid"><label>القسم<select value={department} onChange={e=>{setDepartment(e.target.value);setCategory('DOCUMENT');setInvoiceId('');}}>{actorDepartments(user).map(d=><option key={d} value={d}>{label(d)}</option>)}</select></label><label>نوع الملف<select value={category} onChange={e=>setCategory(e.target.value)}>{['DOCUMENT',...(department==='SALON'?['BEFORE','AFTER']:[]),...(department==='COLLEGE'?['WORK']:[]),...(department==='FINANCE'&&financial(user)?['RECEIPT']:[])].map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label>{department==='FINANCE'&&<label>ربط بالفاتورة (اختياري)<select aria-label="الفاتورة المرتبطة بالمرفق" value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">ملف العميلة فقط</option>{invoices.filter(i=>i.status!=='VOID').map(i=><option key={i.id} value={i.id}>{i.description} · {i.currency} {i.amount}</option>)}</select></label>}</div><input aria-label="رفع ملف" disabled={disabled} type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>{setFile(e.target.files?.[0]??null);e.target.value='';}}/>{file&&<div className="crm-upload-preview"><p>{file.name} · {Math.ceil(file.size/1024)} KB</p>{preview&&<img src={preview} alt="معاينة قبل الحفظ"/>}<button disabled={disabled||file.size>4*1024*1024} onClick={async()=>{try{await onUpload(file,category,department,invoiceId);setFile(null);}catch{/* Parent displays the error and keeps the selected file for retry. */}}}>حفظ المرفق</button><button disabled={disabled} onClick={()=>setFile(null)}>إلغاء</button>{file.size>4*1024*1024&&<p role="alert">حجم الملف يتجاوز 4 MB</p>}</div>}</section>;
}
