'use client';
import {useEffect,useState} from 'react';
import {allowed,type Actor} from '@/lib/crm-access';
import {label} from '@/lib/crm-config';
import DepartmentSpotlight from './DepartmentSpotlight';
import CrmIcon from './CrmIcon';
type Row=Record<string,any>;
async function request(path:string,options?:RequestInit){const r=await fetch(path,{cache:'no-store',...options});const d=await r.json();if(!r.ok)throw Error(d.error??'تعذر إتمام الطلب');return d;}
const date=(v:any)=>v?new Intl.DateTimeFormat('ar',{timeZone:'Asia/Jerusalem',year:'numeric',month:'short',day:'numeric'}).format(new Date(v)):'—';
const time=(v:any)=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jerusalem',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const money=(v:any,currency:string)=>new Intl.NumberFormat('ar',{style:'currency',currency}).format(Number(v??0));
function Status({value}:{value:string}){const tone=['CONFIRMED','CONTACTED','REGISTERED','COMPLETED','ATTENDED'].includes(value)?'green':['DEPOSIT','STUDYING'].includes(value)?'blue':['WAITING_REPLY','PENDING_REPLY','WAITING_DOCUMENTS'].includes(value)?'amber':['NEW','CANCELLED'].includes(value)?'pink':'purple';return <span className={`ref-status ${tone}`}><i/>{label(value)}</span>;}
function NotePanel({customerId,department,user,onSaved}:{customerId?:string;department:string;user:Actor;onSaved:()=>void}){
 const [note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setNote('');setFile(null);setMessage('');},[customerId]);
 useEffect(()=>{if(!file?.type.startsWith('image/')){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function save(){if(!customerId||busy)return;setBusy(true);setMessage('');try{if(note.trim()){await request('/api/crm/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId,department,body:note})});setNote('');}if(file){const body=new FormData();body.set('customerId',customerId);body.set('department',department);body.set('category','DOCUMENT');body.set('file',file);await request('/api/crm-documents',{method:'POST',body});setFile(null);}setMessage('تم الحفظ في الملف');onSaved();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <><textarea aria-label="ملاحظة القسم" placeholder={customerId?'اكتبي ملاحظة قصيرة هنا…':'اختاري سجلًا من الجدول أولًا'} value={note} disabled={!customerId||!allowed(user,'notes',true)||busy} onChange={e=>setNote(e.target.value)}/>{allowed(user,'documents')&&<label className={`ref-file ${!customerId?'disabled':''}`}><CrmIcon name="attach"/>إرفاق صورة أو ملف<small>{file?file.name:'يمكن إرفاق المستندات اللازمة للعمل · حتى 4 MB'}</small><input aria-label="إرفاق ملف من القسم" disabled={!customerId||busy} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>{const picked=e.target.files?.[0];if(picked&&picked.size<=4*1024*1024){setFile(picked);setMessage('');}else if(picked)setMessage('حجم الملف يتجاوز 4 MB');e.target.value='';}}/></label>}{preview&&<img className="ref-preview" src={preview} alt="معاينة المرفق قبل الحفظ"/>}{file&&<button className="crm-link" disabled={busy} onClick={()=>setFile(null)}>إزالة المرفق</button>}<button className="ref-note-save" onClick={save} disabled={!customerId||busy||(!note.trim()&&!file)}><CrmIcon name="note"/>{busy?'جارٍ الحفظ…':'حفظ الملاحظة والمرفق'}</button>{message&&<p role="status">{message}</p>}</>;
}
export default function CrmDepartmentScreen({section,eventId,revision,user,onOpen,onProfile,onEdit,onPayment,onSaved}:{section:string;eventId:string;revision:number;user:Actor;onOpen:(resource:string,filter?:string)=>void;onProfile:(id:string,tab?:string)=>void;onEdit:(resource:string,row:Row)=>void;onPayment:(invoiceId:string)=>void;onSaved:()=>void}){
 const [data,setData]=useState<Row|null>(null),[selected,setSelected]=useState(''),[profile,setProfile]=useState<Row|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;setError('');request(`/api/crm/department-screen?${new URLSearchParams({section,eventId})}`).then(d=>{if(active){setData(d);setSelected(current=>d.rows.some((r:Row)=>r.id===current)?current:d.rows[0]?.id??'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[section,eventId,revision]);
 const row=data?.rows.find((r:Row)=>r.id===selected),customerId=row?.person?.id;
 useEffect(()=>{let active=true;setProfile(null);if(customerId)request(`/api/crm/profile?id=${encodeURIComponent(customerId)}`).then(d=>{if(active)setProfile(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[customerId,revision]);
 const department=section==='college'?'COLLEGE':section==='events'?'EVENT':'SALON';
 async function complete(task:Row){try{await request('/api/crm/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:task.id,completedAt:new Date().toISOString()})});onSaved();}catch(e:any){setError(e.message);}}
 if(error)return <div className="crm-alert" role="alert">{error}</div>;
 if(!data)return <div className="crm-section-summary ref-loading" role="status">جارٍ تحميل مساحة العمل…</div>;
 const title=section==='salon'?'جدول اليوم':section==='college'?'طالبات بحاجة لمتابعة':'متابعة التسجيل';
 const plan=profile?.related?.laserPlans?.rows?.[0];const invoice=profile?.related?.invoices?.rows?.find((i:Row)=>i.id===row?.invoiceId);
 const tasks=<section className="ref-panel ref-tasks"><header><h3><CrmIcon name="tasks"/>مهام اليوم</h3>{allowed(user,'tasks')&&<button className="crm-link" onClick={()=>onOpen('tasks','TODAY')}>عرض الكل ‹</button>}</header><div className="crm-table-wrap"><table className="crm-table ref-table"><thead><tr><th>المهمة</th><th>الوقت</th><th>الحالة</th></tr></thead><tbody>{data.tasks.map((t:Row)=><tr key={t.id}><td><button className="crm-link" onClick={()=>onProfile(t.customerId)}>{t.nextAction||t.reason}<small>{t.customer.name}</small></button></td><td dir="ltr">{time(t.dueAt)}</td><td><input aria-label={`إكمال ${t.reason}`} type="checkbox" checked={false} disabled={!allowed(user,'tasks',true)} onChange={()=>complete(t)}/></td></tr>)}</tbody></table>{!data.tasks.length&&<p className="ref-empty">لا توجد مهام مستحقة اليوم</p>}</div></section>;
 return <div className={`crm-section-summary ref-department ref-${section}`}>
  <DepartmentSpotlight section={section} data={data} user={user} onOpen={onOpen} onEdit={onEdit}/><div className="ref-metrics">{data.cards.map((c:Row)=><button className={`ref-metric ${c.tone}`} key={c.title} disabled={!allowed(user,c.resource)} onClick={()=>onOpen(c.resource,c.filter)}><div><span>{c.title}</span><strong>{c.value}</strong></div><i><CrmIcon name={c.icon} size={32}/></i></button>)}</div>
  <section className="ref-panel ref-main-table"><header><h3><CrmIcon name={section==='salon'?'events':'staff'}/>{title}</h3><button className="crm-link" onClick={()=>onOpen(data.resource)}>عرض الكل ‹</button></header><div className="crm-table-wrap"><table className="crm-table ref-table"><thead><tr>{section==='salon'?<><th>الوقت</th><th>العميلة</th><th>الخدمة</th><th>الموظفة</th><th>حالة الموعد</th></>:<><th>{section==='college'?'الطالبة':'المهتمة'}</th><th>{section==='college'?'الدورة':'الباقة'}</th>{section==='events'&&<th>عدد الأشخاص</th>}<th>{section==='college'?'المرحلة':'حالة التسجيل'}</th><th>آخر تواصل</th><th>الخطوة الجاية</th>{section==='college'&&<th>المسؤولة</th>}</>}<th aria-label="إجراءات"/></tr></thead><tbody>{data.rows.map((r:Row)=><tr key={r.id} className={selected===r.id?'selected':''}>
   {section==='salon'?<><td dir="ltr">{time(r.startsAt)}</td><td><button className="ref-person" onClick={()=>setSelected(r.id)}>{r.person?.name??r._labels?.customerId??'—'}</button></td><td>{r._labels?.serviceId}</td><td>{r._labels?.staffId??'غير مسندة'}</td><td><Status value={r.status}/></td></>:<><td><button className="ref-person" onClick={()=>setSelected(r.id)}><CrmIcon name="customers" size={18}/>{r.person?.name??r.name}</button></td><td>{section==='college'?r.interestedCourse||'—':r._labels?.packageId||r._labels?.eventId||'—'}</td>{section==='events'&&<td>{r.partySize}</td>}<td><Status value={r.stage??r.status}/></td><td>{date(r.person?.lastContactAt)}<small dir="ltr">{r.person?.lastContactAt?time(r.person.lastContactAt):''}</small></td><td>{r.nextAction?<span className="ref-action-pill">{r.nextAction}</span>:<button className="crm-link" disabled={!r.person?.id} onClick={()=>onProfile(r.person.id,'tasks')}>تحديد متابعة</button>}</td>{section==='college'&&<td>{r.person?.ownerName??'—'}</td>}</>}
   <td><div className="ref-row-actions">{r.person?.phone&&<a aria-label={`اتصال ${r.person.name}`} href={`tel:+${r.person.phone}`}><CrmIcon name="phone" size={17}/></a>}<button aria-label={`تفاصيل ${r.person?.name??r.name??'الموعد'}`} onClick={()=>setSelected(r.id)}>•••</button>{allowed(user,data.resource,true)&&<button title="تعديل السجل" aria-label={`تعديل ${r.person?.name??'الموعد'}`} onClick={()=>onEdit(data.resource,r)}><CrmIcon name="note" size={17}/></button>}</div></td></tr>)}</tbody></table>{!data.rows.length&&<p className="ref-empty">{section==='salon'?'لا توجد مواعيد لهذا اليوم':'لا توجد سجلات في نطاقك بعد'}</p>}</div></section>
  <div className="ref-bottom-grid">
   <section className="ref-panel ref-notes"><header><h3><CrmIcon name="note"/>{section==='college'?'ملاحظات وملفات الطالبة':section==='events'?'ملاحظات وملفات المهتمة':'ملاحظاتي'}</h3></header>{row?.person&&<div className="ref-selected"><CrmIcon name="customers"/>{row.person.name}</div>}<NotePanel customerId={customerId} department={department} user={user} onSaved={onSaved}/><small className="ref-privacy"><CrmIcon name="lock" size={15}/>الملفات تظهر للمخوّلات فقط</small></section>
   <section className="ref-panel ref-details"><header><h3><CrmIcon name={section==='events'?'note':'customers'}/>{section==='college'?'معلومات الطالبة':section==='events'?'تفاصيل التسجيل':'ملف العميلة'}</h3></header>{row?.person?<><div className="ref-selected"><CrmIcon name="customers"/>{row.person.name}</div><dl><div><dt>رقم الهاتف</dt><dd><a dir="ltr" href={`tel:+${row.person.phone}`}>+{row.person.phone}</a></dd></div>{section==='events'?<><div><dt>الإيفنت</dt><dd>{row._labels?.eventId}</dd></div><div><dt>الباقة</dt><dd>{row._labels?.packageId??'—'}</dd></div><div><dt>عدد الأشخاص</dt><dd>{row.partySize}</dd></div><div><dt>المرافقة</dt><dd>{row.companion||'لا يوجد'}</dd></div><div><dt>السكن والطيران</dt><dd>{row.hotel?row.hotelName||'فندق مشمول':'دون فندق'} · {row.flight?'طيران مشمول':'دون طيران'}</dd></div>{data.canFinance&&invoice&&<div className="ref-money"><span>السعر<strong>{money(invoice.amount,invoice.currency)}</strong></span><span>المدفوع<strong>{money(invoice.paidAmount,invoice.currency)}</strong></span><span>المتبقي<strong>{money(invoice.balance,invoice.currency)}</strong></span></div>}</>:section==='college'?<><div><dt>الدورة</dt><dd>{row.interestedCourse||profile?.related?.enrollments?.rows?.[0]?._labels?.courseId||'—'}</dd></div><div><dt>البريد الإلكتروني</dt><dd>{row.person.email||'—'}</dd></div><div><dt>المسؤولة</dt><dd>{row.person.ownerName||'—'}</dd></div><div><dt>المستندات الناقصة</dt><dd>{row.missingDocuments?.join('، ')||'لا توجد أوراق ناقصة مسجلة'}</dd></div></>:<><div><dt>الموعد</dt><dd>{date(row.startsAt)} · {time(row.startsAt)}</dd></div><div><dt>الخدمة</dt><dd>{row._labels?.serviceId}</dd></div>{plan&&<div><dt>الجلسات</dt><dd>{plan.sessionsUsed} من {plan.sessionsTotal}</dd></div>}<div><dt>المتابعة القادمة</dt><dd>{date(profile?.customer.followUpAt)}</dd></div></>}</dl>{data.canFinance&&invoice&&!['PAID','VOID'].includes(invoice.status)&&<button className="ref-note-save" onClick={()=>onPayment(invoice.id)}><CrmIcon name="finance"/>إضافة دفعة</button>}<button className="ref-note-save" onClick={()=>onProfile(customerId)}>عرض تفاصيل {section==='college'?'الطالبة':'العميلة'}</button></>:<p className="ref-empty">اختاري اسمًا من الجدول لعرض التفاصيل</p>}</section>
   <div className="ref-side-panels">{section==='college'?<section className="ref-panel"><header><h3><CrmIcon name="events"/>الدورات القادمة</h3><button className="crm-link" onClick={()=>onOpen('collegeCourses')}>عرض الكل ‹</button></header><div className="crm-table-wrap"><table className="crm-table ref-table"><thead><tr><th>الدورة</th><th>التاريخ</th><th>المقاعد</th></tr></thead><tbody>{data.courses.map((c:Row)=><tr key={c.id}><td>{c.title}<small>{c._labels?.trainerId??c.groupName}</small></td><td>{date(c.startsAt)}</td><td dir="ltr">{c.enrolledCount} / {c.capacity}</td></tr>)}</tbody></table>{!data.courses.length&&<p className="ref-empty">لا توجد دورات قادمة في نطاقك</p>}</div></section>:tasks}{section==='salon'&&(data.shifts||data.shiftMessage)&&<section className="ref-panel ref-shifts"><header><h3><CrmIcon name="clock"/>جدول دوامي</h3></header><div>{data.shifts?.map((s:Row,i:number)=><article key={i}><CrmIcon name={i?'clock':'sun'} size={27}/><span>الفترة {i+1}<strong dir="ltr">{s.start} – {s.end}</strong></span></article>)}</div>{!data.shifts?.length&&<p>{data.shiftMessage||'لا توجد فترات دوام اليوم'}</p>}</section>}</div>
  </div>
 </div>;
}
