'use client';
import { useEffect, useState } from 'react';
import { label } from '@/lib/crm-config';

export default function CrmSectionSummary({section,eventId,revision,onOpen,onProfile}:{section:string;eventId:string;revision:number;onOpen:(resource:string,filter?:string,ownerId?:string)=>void;onProfile:(id:string)=>void}){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;setData(null);setError('');fetch(`/api/crm/section-summary?${new URLSearchParams({section,eventId})}`,{cache:'no-store'}).then(async r=>{if(r.status===403)return null;const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[section,eventId,revision]);
 if(error)return <p role="alert">{error}</p>;
 if(!data)return null;
 const money=(amount:number,currency:string)=>new Intl.NumberFormat('ar',{style:'currency',currency}).format(amount);
 return <div className="crm-section-summary">
  <div className="crm-stats">{data.cards.map((c:any)=><article key={c.title}><small>{c.title}</small><strong>{c.value}</strong><button onClick={()=>onOpen(c.resource,c.filter)}>فتح السجلات ←</button></article>)}{data.balances?.map((b:any)=><article key={b.currency}><small>المبالغ المحصلة · {b.currency}</small><strong>{money(Number(b._sum.paidAmount),b.currency)}</strong><small>المتبقي {money(Number(b._sum.agreedAmount)-Number(b._sum.paidAmount),b.currency)}</small></article>)}{data.valuation?.map((v:any)=><article key={v.currency}><small>قيمة المخزون بسعر الشراء</small><strong>{money(v.amount,v.currency)}</strong></article>)}</div>
  {data.monthSales?.length>0&&<div className="crm-stats">{data.monthSales.map((s:any)=><article key={s.currency}><small>مبيعات الشهر · {s.currency}</small><strong>{money(Number(s._sum.amount),s.currency)}</strong><small>المحصّل لهذه الفواتير {money(Number(s._sum.paidAmount),s.currency)}</small></article>)}</div>}
  {data.followUps?.length>0&&<section className="crm-panel"><div className="crm-panel-heading"><h3>المتابعات المطلوبة</h3><button onClick={()=>onOpen('tasks')}>عرض الكل</button></div><div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>الاسم</th><th>الطلب والخطوة القادمة</th><th>الحالة</th><th>تواصل</th></tr></thead><tbody>{data.followUps.map((t:any)=><tr key={t.id}><td><button className="crm-link" onClick={()=>onProfile(t.customerId)}>{t.customer.name}</button></td><td>{t.reason}<p>{t.nextAction}</p></td><td>{label(t.outcome)}</td><td><a href={`https://wa.me/${t.customer.phone}`} target="_blank" rel="noopener noreferrer">واتساب</a></td></tr>)}</tbody></table></div></section>}
  {data.courses?.length>0&&<section className="crm-panel"><h3>الكورسات المفتوحة · المقاعد والتسجيل</h3><div className="crm-course-cards">{data.courses.map((c:any)=><article key={c.id}><div><strong>{c.title}</strong><p>{c.groupName} · {label(c.status)}</p><small>المقاعد المتبقية: {c.remainingSeats}</small></div><span className="crm-seat-count">{c.enrolledCount}/{c.capacity}</span></article>)}</div><button onClick={()=>onOpen('collegeCourses')}>إدارة الكورسات والحضور</button></section>}
  {data.team&&<section className="crm-panel"><h3>الفريق · المهام والمواعيد والصلاحيات</h3><div className="crm-team-cards">{data.team.map((s:any)=><article key={s.id}><header><span className="crm-avatar">{s.name.slice(0,1)}</span><div><strong>{s.name}</strong><p>{s.title||'موظفة'}</p></div></header><dl>{s.tasks!==null&&<div><dt>متابعات اليوم</dt><dd>{s.tasks}</dd></div>}<div><dt>مواعيد اليوم</dt><dd>{s.appointments}</dd></div><div><dt>الصلاحية</dt><dd>{s.accountRole?label(s.accountRole):'لا يوجد حساب مرتبط'}</dd></div></dl>{s.ownerId&&s.tasks!==null&&<button onClick={()=>onOpen('tasks','TODAY',s.ownerId)}>فتح المتابعات</button>}</article>)}</div></section>}
 </div>;
}
