'use client';
import { dateInput } from '@/lib/date-input';
import { useEffect, useState } from 'react';

type Item=Record<string,any>;
export default function CustomerPortal({user}:{user:{name:string;role:string}}) {
  const [services,setServices]=useState<Item[]>([]),[requests,setRequests]=useState<Item[]>([]),[serviceId,setServiceId]=useState(''),[preferredAt,setPreferredAt]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
  async function load(){const [serviceResponse,requestResponse]=await Promise.all([fetch('/api/customer/services'),fetch('/api/service-requests')]);if(serviceResponse.ok)setServices(await serviceResponse.json());if(requestResponse.ok)setRequests(await requestResponse.json());}
  useEffect(()=>{load();},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');const response=await fetch('/api/service-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId,preferredAt:new Date(preferredAt).toISOString(),notes})});const result=await response.json();setSaving(false);if(!response.ok){setMessage(result.error||'Could not send request');return;}setServiceId('');setPreferredAt('');setNotes('');setMessage('Request sent successfully');await load();}
  return <main className="customerPortal"><header><div><strong>Sii Bello Saloon</strong><small>Customer Portal</small></div><div><span>{user.name}</span><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/login';}}>Sign out</button></div></header><div className="customerPortalBody"><section className="customerWelcome"><span>✦</span><div><h1>Welcome, {user.name}</h1><p>Choose a service and send your preferred appointment time.</p></div></section><div className="customerColumns"><form className="requestForm" onSubmit={submit}><h2>Request a service</h2><label>Service<select required value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">Choose service</option>{services.map(s=><option value={s.id} key={s.id}>{s.name} · ₪{Number(s.price)} · {s.durationMinutes} min</option>)}</select></label><label>Preferred time<input type="datetime-local" required min={dateInput(new Date())} value={preferredAt} onChange={e=>setPreferredAt(e.target.value)}/></label><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} /></label>{message&&<div className={message.includes('success')?'success':'error'}>{message}</div>}<button className="primary" disabled={saving}>{saving?'Sending...':'Send request'}</button></form><section className="requestHistory"><h2>My requests</h2>{requests.map(r=><article key={r.id}><div><strong>{r.service.name}</strong><small>{new Date(r.preferredAt).toLocaleString()}</small>{r.notes&&<p>{r.notes}</p>}</div><span className={'requestStatus '+r.status.toLowerCase()}>{r.status}</span>{r.adminNote&&<p className="adminReply">Salon: {r.adminNote}</p>}</article>)}{!requests.length&&<p>No requests yet.</p>}</section></div></div></main>;
}
