'use client';
import {useEffect,useState} from 'react';
import {ServiceDetailsFields} from './ServiceCatalogue';
import LaserRegistrationCatalogue,{type LaserCatalogueService} from './LaserRegistrationCatalogue';
import {quoteService} from '@/lib/service-selection';
type Entry={serviceId:string;details:Record<string,any>};
type Item=LaserCatalogueService&{kind:'SERVICE'|'COLLEGE'|'EVENT';category:string;currency:string;description?:string;durationMinutes?:number;imageUrl?:string};
const names:Record<string,string>={LASER:'الليزر',HAIR:'صالون الشعر',NAILS:'الأظافر',COLLEGE:'الكلية',EVENT:'الإيفنتات',OTHER:'خدمات الصالون الأخرى'};
const price=(v:unknown,currency='ILS')=>new Intl.NumberFormat('ar',{style:'currency',currency}).format(Number(v));
export function CustomerServices({serviceId,value,onChange,customer,canRegisterLaser,interests,onInterestsChange}:{serviceId:string;value:any;customer:Record<string,any>;canRegisterLaser:boolean;interests:any;onInterestsChange:(v:any)=>void;onChange:(id:string|null,v:any)=>void}){
 const [rows,setRows]=useState<Item[]>([]),[known,setKnown]=useState<Record<string,Item>>({}),[categories,setCategories]=useState<string[]>([]),[category,setCategory]=useState(''),[detail,setDetail]=useState<Item|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const entries:Entry[]=Array.isArray(value?.services)?value.services:serviceId?[{serviceId,details:value??{}}]:[];
 const chosenInterests:{kind:string;id:string;name?:string}[]=interests?.items??[];
 useEffect(()=>{let active=true;const controller=new AbortController();setLoading(true);fetch('/api/crm/catalogue?q='+encodeURIComponent(query),{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error??'تعذر تحميل الكتالوج');if(active){setRows(d.rows);setCategories(d.categories);setKnown(old=>({...old,...Object.fromEntries(d.rows.map((x:Item)=>[x.id,x]))}));}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[query]);
 const update=(next:Entry[])=>onChange(next[0]?.serviceId??null,{services:next});
 const personalReady=()=>{if(!customer.name?.trim()||!customer.phone||!['FEMALE','MALE'].includes(customer.gender)){setError('أكملي الاسم والهاتف واختاري الجنس أولًا');return false;}setError('');return true;};
 const choose=(s:Item,checked:boolean)=>{
  if(checked&&!personalReady())return;
  if(s.kind!=='SERVICE'){onInterestsChange({items:checked?[...chosenInterests,{kind:s.kind,id:s.id}]:chosenInterests.filter(x=>x.kind!==s.kind||x.id!==s.id)});return;}
  if(checked&&s.department==='LASER'&&!canRegisterLaser){setError('ليس لديك صلاحية تسجيل باقات الليزر');return;}
  const old=entries.find(x=>x.serviceId===s.id);
  if(!checked&&old&&Object.keys(old.details).length&&!window.confirm('إزالة الخدمة وتفاصيلها من الاختيارات؟ تبقى الباقات المسجلة سابقًا في ملف العميل.'))return;
  update(checked?[...entries,{serviceId:s.id,details:s.department==='LASER'?{gender:customer.gender}:{}}]:entries.filter(x=>x.serviceId!==s.id));
  if(checked)setDetail(s);
 };
 const back=()=>{setDetail(null);setError('');};
 if(detail){const entry=entries.find(x=>x.serviceId===detail.id);if(detail.department==='LASER')return <LaserRegistrationCatalogue service={detail} customer={customer} value={entry?.details??{}} onChange={details=>update(entries.map(x=>x.serviceId===detail.id?{...x,details}:x))} onClose={back}/>;
  let quote;let quoteError='';try{quote=quoteService(detail,entry?.details??{});}catch(e){quoteError=e instanceof Error?e.message:'راجعي الاختيارات';}
  return <section className="customer-catalogue-detail" aria-label="تفاصيل الخدمة المختارة"><button type="button" onClick={back}>العودة إلى {names[category]}</button><h2>{detail.name}</h2><ServiceDetailsFields service={detail} value={entry?.details??{}} onChange={details=>update(entries.map(x=>x.serviceId===detail.id?{...x,details}:x))}/>{quoteError&&<p role="alert">{quoteError}</p>}<footer><strong>السعر النهائي: {quote?price(quote.finalPrice):'اختاري التفاصيل'}</strong><button type="button" className="crm-primary" disabled={!quote} onClick={back}>اعتماد الخدمة</button></footer></section>;
 }
 return <section className="customer-catalogue" aria-label="كتالوج الخدمات"><p>البيانات الشخصية ← القسم الرئيسي ← الخدمة وتفاصيلها</p>{error&&<p role="alert" className="crm-alert">{error}</p>}{!category?<div className="customer-category-grid">{categories.map(c=><button type="button" key={c} onClick={()=>{if(personalReady()){setCategory(c);setQuery('');}}}><strong>{names[c]}</strong><small>فتح الخدمات</small></button>)}</div>:<><header><h3>{names[category]}</h3><button type="button" onClick={()=>{setCategory('');setQuery('');}}>جميع الأقسام</button></header><input aria-label="بحث الخدمات المطلوبة" placeholder="بحث في الكتالوج…" value={query} onChange={e=>{setError('');setQuery(e.target.value);}}/><div className="customer-catalogue-list">{rows.filter(s=>s.category===category).map(s=>{const checked=s.kind==='SERVICE'?entries.some(e=>e.serviceId===s.id):chosenInterests.some(e=>e.kind===s.kind&&e.id===s.id);return <article key={s.kind+s.id}><label><input type="checkbox" checked={checked} onChange={e=>choose(s,e.target.checked)}/><span>{s.name}</span></label>{s.imageUrl&&<img src={s.imageUrl} alt=""/>}<strong>{s.configuration?.variants?.length?'حسب الخيار المحدد':price(s.price,s.currency)}</strong>{s.durationMinutes&&<small>{s.durationMinutes} دقيقة</small>}{s.description&&<p>{s.description}</p>}{checked&&s.kind==='SERVICE'&&<button type="button" onClick={()=>setDetail(s)}>{s.department==='LASER'?'فتح كتالوج الليزر':'تفاصيل الخدمة'}</button>}</article>;})}</div>{!loading&&!rows.some(s=>s.category===category)&&<p>لا توجد خدمات مضافة هنا بعد. تُضاف الخدمات والأسعار من إعدادات القسم.</p>}{['COLLEGE','EVENT'].includes(category)&&<small>يُحفظ الاختيار كاهتمام في ملف العميل. التسجيل المؤكد والدفعات لهما إجراء مستقل.</small>}</>}{loading&&<p role="status">جارٍ تحميل الكتالوج…</p>}
 {(entries.length>0||chosenInterests.length>0)&&<aside className="catalogue-selected"><h4>الخدمات المختارة</h4>{entries.map(e=><span key={e.serviceId}>{known[e.serviceId]?.name??'خدمة مسجلة'}<button type="button" aria-label={`إزالة ${known[e.serviceId]?.name??'الخدمة المختارة'}`} onClick={()=>{if(!Object.keys(e.details).length||window.confirm('إزالة اختيار الخدمة وتفاصيله؟'))update(entries.filter(x=>x.serviceId!==e.serviceId));}}>×</button></span>)}{chosenInterests.map(e=><span key={e.kind+e.id}>{known[e.id]?.name??e.name??names[e.kind]}<button type="button" aria-label="إزالة اهتمام" onClick={()=>onInterestsChange({items:chosenInterests.filter(x=>x.kind!==e.kind||x.id!==e.id)})}>×</button></span>)}</aside>}</section>;
}
