'use client';
import { dateInput } from '@/lib/date-input';
import { useEffect, useState } from 'react';

type Item=Record<string,any>;
export default function CustomerPortal({user}:{user:{name:string;role:string}}) {
  const [services,setServices]=useState<Item[]>([]),[requests,setRequests]=useState<Item[]>([]),[serviceId,setServiceId]=useState(''),[preferredAt,setPreferredAt]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
  async function load(){try{const [serviceResponse,requestResponse]=await Promise.all([fetch('/api/customer/services'),fetch('/api/service-requests')]);if(serviceResponse.ok)setServices(await serviceResponse.json());if(requestResponse.ok)setRequests(await requestResponse.json());}catch{setMessage('تعذر تحميل البيانات');}}
  useEffect(()=>{load();},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');try{const response=await fetch('/api/service-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId,preferredAt:new Date(preferredAt).toISOString(),notes})});const result=await response.json();setSaving(false);if(!response.ok){setMessage(result.error||'تعذر إرسال الطلب');return;}setServiceId('');setPreferredAt('');setNotes('');setMessage('تم إرسال الطلب بنجاح');await load();}catch{setMessage('تعذر الاتصال بالخادم؛ حاولي مرة أخرى.');}finally{setSaving(false);}}
  return <main className="customerPortal"><header><div><strong>Sii Bello Saloon</strong><small>بوابة العميلة</small></div><div><span>{user.name}</span><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/login';}}>خروج</button></div></header><div className="customerPortalBody"><section className="customerWelcome"><span>✦</span><div><h1>مرحبًا، {user.name}</h1><p>اختاري الخدمة وموعدك المفضل.</p></div></section><div className="customerColumns"><form className="requestForm" onSubmit={submit}><h2>طلب خدمة</h2><label>الخدمة<select required value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">اختاري الخدمة</option>{services.map(s=><option value={s.id} key={s.id}>{s.name} · ₪{Number(s.price)} · {s.durationMinutes} min</option>)}</select></label><label>الموعد المفضل<input type="datetime-local" required min={dateInput(new Date())} value={preferredAt} onChange={e=>setPreferredAt(e.target.value)}/></label><label>ملاحظات<textarea value={notes} onChange={e=>setNotes(e.target.value)} /></label>{message&&<div className={message.includes('بنجاح')?'success':'error'}>{message}</div>}<button className="primary" disabled={saving}>{saving?'جارٍ الإرسال…':'إرسال الطلب'}</button></form><section className="requestHistory"><h2>طلباتي</h2>{requests.map(r=><article key={r.id}><div><strong>{r.service.name}</strong><small>{new Date(r.preferredAt).toLocaleString()}</small>{r.notes&&<p>{r.notes}</p>}</div><span className={'requestStatus '+r.status.toLowerCase()}>{r.status}</span>{r.adminNote&&<p className="adminReply">الصالون: {r.adminNote}</p>}</article>)}{!requests.length&&<p>لا توجد طلبات بعد.</p>}</section></div></div></main>;
}
