'use client';
import {allowed,type Actor} from '@/lib/crm-access';
import {label} from '@/lib/crm-config';
import CrmIcon from './CrmIcon';
export default function DepartmentSpotlight({section,data,user,onOpen,onEdit}:{section:string;data:any;user:Actor;onOpen:(r:string,f?:string)=>void;onEdit:(r:string,row?:any)=>void}){
 if(section==='college')return <section className="crm-panel oct-courses"><div className="crm-panel-heading"><h3><CrmIcon name="college"/> الكلية — إدارة الدورات</h3>{allowed(user,'collegeCourses',true)&&<button className="crm-primary" onClick={()=>onEdit('collegeCourses')}>إضافة دورة جديدة</button>}</div><div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>اسم الدورة</th><th>المدربة</th><th>البداية</th><th>الحالة</th><th>المسجلات / السعة</th><th>التفاصيل</th></tr></thead><tbody>{data.courses?.map((c:any)=><tr key={c.id}><td><strong>{c.title}</strong><small>{c.groupName}</small></td><td>{c._labels?.trainerId??'—'}</td><td>{c.startsAt?new Date(c.startsAt).toLocaleDateString('ar'):'غير محدد'}</td><td><span className="crm-badge purple">{label(c.status)}</span></td><td>{c.enrolledCount} / {c.capacity}</td><td><button onClick={()=>allowed(user,'collegeCourses',true)?onEdit('collegeCourses',c):onOpen('collegeCourses')}>عرض الدورة</button></td></tr>)}</tbody></table></div>{!data.courses?.length&&<p>لا توجد دورات قادمة في نطاقك.</p>}<button className="crm-link" onClick={()=>onOpen('collegeCourses')}>جميع الدورات والمجموعات</button></section>;
 if(section==='events'&&data.event){const e=data.event;return <section className="crm-panel oct-event"><div className="crm-panel-heading"><h2><CrmIcon name="events" size={32}/> {e.name}</h2><button onClick={()=>onOpen('events')}>عرض ملف الفعالية</button></div><p>{e.startsAt?new Date(e.startsAt).toLocaleDateString('ar',{timeZone:'Asia/Dubai'}):'التاريخ غير محدد'} · {e.location??'الموقع غير محدد'} · {e.currency}</p>{e.notes&&<p>{e.notes}</p>}<div className="oct-event-flow">{[['NEW','استفسار','message'],['REGISTRATIONS','تسجيل','note'],['DEPOSIT','دفعة وتأكيد','finance']].map(([filter,title,icon])=><button key={filter} onClick={()=>onOpen('eventLeads',filter)}><CrmIcon name={icon} size={30}/>{title}</button>)}</div></section>;}
 return null;
}
