'use client';
import { dateInput } from '@/lib/date-input';
import { useEffect,useState } from 'react';
type Data={customer:{name:string;phone:string;email:string|null};services:any[];requests:any[];workingHours:any[]};
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export default function PhoneBooking(){
  const [step,setStep]=useState<'phone'|'code'|'portal'>('phone'),[phone,setPhone]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[devCode,setDevCode]=useState(''),[data,setData]=useState<Data|null>(null),[serviceId,setServiceId]=useState(''),[date,setDate]=useState(''),[slots,setSlots]=useState<string[]>([]),[slot,setSlot]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function load(){const response=await fetch('/api/booking/data',{cache:'no-store'});if(response.ok){setData(await response.json());setStep('portal');}}
  useEffect(()=>{load();},[]);
  async function requestCode(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const response=await fetch('/api/booking/request-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone})});const result=await response.json();setBusy(false);if(!response.ok){setError(result.error);return;}setDevCode(result.devCode||'');setStep('code');}
  async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const response=await fetch('/api/booking/verify-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,code,name})});const result=await response.json();setBusy(false);if(!response.ok){setError(result.error);return;}await load();}
  async function getSlots(nextService=serviceId,nextDate=date){setSlot('');if(!nextService||!nextDate){setSlots([]);return;}const response=await fetch(`/api/booking/slots?serviceId=${encodeURIComponent(nextService)}&date=${encodeURIComponent(nextDate)}`);setSlots(response.ok?await response.json():[]);}
  async function book(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');const response=await fetch('/api/booking/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId,preferredAt:slot,notes})});const result=await response.json();setBusy(false);if(!response.ok){setError(result.error);await getSlots();return;}setMessage('Your request was sent to the salon for approval.');setServiceId('');setDate('');setSlot('');setSlots([]);setNotes('');await load();}
  if(step!=='portal')return <main className="phoneEntry"><div className="phoneEntryCard"><a href="/login" className="staffLink">Staff login</a><div className="bookingMark">✦</div><h1>Sii Bello Saloon</h1><p>{step==='phone'?'Enter your WhatsApp number to book an appointment.':'Enter the 6-digit code sent to WhatsApp.'}</p>{step==='phone'?<form onSubmit={requestCode}><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} /></label><label>WhatsApp phone number<input required type="tel" placeholder="972501234567" value={phone} onChange={e=>setPhone(e.target.value)} /></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Sending...':'Send verification code'}</button></form>:<form onSubmit={verify}><label>Verification code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} /></label>{devCode&&<div className="devCode">Local testing code: <strong>{devCode}</strong></div>}{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Checking...':'Verify and continue'}</button><button type="button" className="secondary wide" onClick={()=>setStep('phone')}>Change number</button></form>}</div></main>;
  return <main className="bookingPortal"><header><div><strong>Sii Bello Saloon</strong><small>APPOINTMENT REQUESTS</small></div><div><span>{data?.customer.name}</span><button onClick={async()=>{await fetch('/api/booking/logout',{method:'POST'});setData(null);setStep('phone');}}>Exit</button></div></header><div className="bookingBody"><section className="bookingIntro"><h1>Book your appointment</h1><p>Choose a service, date, and an available time. The salon will confirm your request.</p></section><div className="bookingLayout"><form className="bookingForm" onSubmit={book}><h2>New request</h2><label>Service<select required value={serviceId} onChange={e=>{setServiceId(e.target.value);getSlots(e.target.value,date);}}><option value="">Choose service</option>{data?.services.map(s=><option key={s.id} value={s.id}>{s.name} · ₪{Number(s.price)} · {s.durationMinutes} min</option>)}</select></label><label>Date<input required type="date" min={dateInput(new Date()).slice(0,10)} value={date} onChange={e=>{setDate(e.target.value);getSlots(serviceId,e.target.value);}} /></label><fieldset><legend>Available time</legend><div className="slotGrid">{slots.map(s=><button type="button" key={s} className={slot===s?'selected':''} onClick={()=>setSlot(s)}>{new Date(s).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</button>)}</div>{date&&serviceId&&!slots.length&&<p className="noSlots">No available times on this day.</p>}</fieldset><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} /></label>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="primary wide" disabled={busy||!slot}>{busy?'Sending...':'Send appointment request'}</button></form><aside><section className="hoursCard"><h2>Working hours</h2>{data?.workingHours.map(h=><div key={h.id}><span>{dayNames[h.dayOfWeek]}</span><strong>{h.active?`${h.openTime}–${h.closeTime}`:'Closed'}</strong></div>)}</section><section className="publicRequests"><h2>My requests</h2>{data?.requests.map(r=><article key={r.id}><div><strong>{r.service.name}</strong><small>{new Date(r.preferredAt).toLocaleString()}</small></div><span className={'requestStatus '+r.status.toLowerCase()}>{r.status}</span>{r.adminNote&&<p>{r.adminNote}</p>}</article>)}{!data?.requests.length&&<p>No requests yet.</p>}</section></aside></div></div></main>;
}
