'use client';
import { useEffect, useState } from 'react';
type Item=Record<string,any>;
export default function RequestsAdmin({isGod,canDelete}:{isGod:boolean;canDelete:boolean}){
  const [requests,setRequests]=useState<Item[]>([]),[logs,setLogs]=useState<Item[]>([]),[notifications,setNotifications]=useState<Item[]>([]),[note,setNote]=useState<Record<string,string>>({}),[error,setError]=useState(''),[view,setView]=useState<'requests'|'audit'>('requests');
  async function load(){const response=await fetch('/api/service-requests',{cache:'no-store'});if(response.ok)setRequests(await response.json());if(isGod){const logResponse=await fetch('/api/audit-logs',{cache:'no-store'});if(logResponse.ok){const result=await logResponse.json();setLogs(result.auditLogs);setNotifications(result.notificationLogs);}}}
  useEffect(()=>{load();},[]);
  async function review(id:string,decision:'APPROVED'|'REJECTED'){setError('');const response=await fetch('/api/service-requests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,decision,adminNote:note[id]||''})});const result=await response.json();if(!response.ok){setError(result.error||'Could not review request');return;}await load();}
  async function remove(id:string){if(!window.confirm('Delete this service request?'))return;const response=await fetch('/api/service-requests',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const result=await response.json();if(!response.ok){setError(result.error||'Could not delete request');return;}await load();}
  return <div><div className="workspaceTabs"><button className={view==='requests'?'on':''} onClick={()=>setView('requests')}>Service requests</button>{isGod&&<button className={view==='audit'?'on':''} onClick={()=>setView('audit')}>Activity & notifications</button>}</div>{error&&<div className="error">{error}</div>}{view==='requests'?<div className="requestsGrid">{requests.map(r=><article className="requestAdminCard" key={r.id}><header><div><strong>{r.customer.name}</strong><small>{r.customer.phone} · {r.customer.email||'No email'}</small></div><span className={'requestStatus '+r.status.toLowerCase()}>{r.status}</span></header><h3>{r.service.name}</h3><p><b>Preferred:</b> {new Date(r.preferredAt).toLocaleString()}</p><p>{r.notes||'No customer note'}</p>{r.status==='PENDING'?<><textarea placeholder="Optional reply to customer" value={note[r.id]||''} onChange={e=>setNote({...note,[r.id]:e.target.value})}/><div className="reviewButtons"><button className="approve" onClick={()=>review(r.id,'APPROVED')}>Approve & create appointment</button><button className="reject" onClick={()=>review(r.id,'REJECTED')}>Decline</button></div></>:<p className="reviewedBy">Reviewed by {r.reviewedBy?.name||'—'} {r.adminNote&&`· ${r.adminNote}`}</p>}{canDelete&&<button className="dangerButton requestDelete" onClick={()=>remove(r.id)}>Delete request</button>}</article>)}{!requests.length&&<div className="empty">No service requests.</div>}</div>:<><h2 className="logHeading">Activity log</h2><div className="workspaceTable"><table><thead><tr><th>When</th><th>User</th><th>Role</th><th>Action</th><th>Table</th><th>Record</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{new Date(l.createdAt).toLocaleString()}</td><td>{l.actorName}</td><td>{l.actorRole}</td><td>{l.action}</td><td>{l.entity}</td><td>{l.entityId||'—'}</td></tr>)}</tbody></table></div><h2 className="logHeading">Notification delivery</h2><div className="workspaceTable"><table><thead><tr><th>When</th><th>Channel</th><th>Recipient</th><th>Event</th><th>Status</th><th>Error</th></tr></thead><tbody>{notifications.map(l=><tr key={l.id}><td>{new Date(l.createdAt).toLocaleString()}</td><td>{l.channel}</td><td>{l.recipient}</td><td>{l.event}</td><td><span className={'requestStatus '+l.status.toLowerCase()}>{l.status}</span></td><td>{l.error||'—'}</td></tr>)}</tbody></table></div></>}</div>;
}
