'use client';
import type {Selection,ServiceConfiguration} from '@/lib/service-selection';
const kinds=[['CUT','قص الشعر'],['COLOR','صبغة'],['EXTENSIONS','وصلات'],['TREATMENT','علاج'],['KERATIN','تمليس / كيراتين']];
export function ServicePriceOptions({configuration,value,onChange}:{configuration?:ServiceConfiguration;value:Selection;onChange:(v:Selection)=>void}){
 const variants=configuration?.variants??[];
 return <>{variants.length>0&&<fieldset className="catalogue-price-options"><legend>خيارات الخدمة والأسعار المعتمدة</legend>{variants.filter(v=>!value.kind||!v.kind||v.kind===value.kind).map(v=><label key={v.id}><input type="radio" name="service-price-option" checked={value.variantId===v.id} onChange={()=>onChange({notes:value.notes,kind:v.kind??value.kind,variantId:v.id,...(v.hairLength?{hairLength:v.hairLength}:{}),...(v.extensionColor?{extensionColor:v.extensionColor}:{}),...(v.extensionLength?{extensionLength:v.extensionLength}:{}),...(v.extensionQuantity?{extensionQuantity:v.extensionQuantity}:{})})}/><span>{v.name}</span><strong>{v.price} ₪</strong></label>)}</fieldset>}</>;
}
export function ServicePriceEditor({value,onChange}:{value:ServiceConfiguration;onChange:(v:ServiceConfiguration)=>void}){
 const variants=value.variants??[];const change=(id:string,field:string,v:any)=>onChange({...value,variants:variants.map(x=>x.id===id?{...x,[field]:v}:x)});
 return <details className="catalogue-price-editor"><summary>خيارات الخدمة والأسعار التفصيلية</summary><p>أضيفي خيارًا لكل سعر معتمد، مثل قص شعر قصير أو طويل، أو وصلات بلون وطول وكمية محددة. لا تُضاف أسعار تلقائيًا.</p>{variants.map(v=><fieldset key={v.id}><label>اسم خيار الخدمة<input value={v.name} onChange={e=>change(v.id,'name',e.target.value)} placeholder="مثل: قص شعر طويل"/></label><label>السعر المعتمد<input type="number" min="0" step="0.01" value={v.price} onChange={e=>change(v.id,'price',Number(e.target.value))}/></label><label>نوع خدمة الشعر<select value={v.kind??''} onChange={e=>{const next={id:v.id,name:v.name,price:v.price,...(e.target.value?{kind:e.target.value}:{})};onChange({...value,variants:variants.map(x=>x.id===v.id?next:x)});}}><option value="">خدمة أخرى</option>{kinds.map(([k,t])=><option key={k} value={k}>{t}</option>)}</select></label>{v.kind&&<label>طول الشعر<select value={v.hairLength??''} onChange={e=>change(v.id,'hairLength',e.target.value||undefined)}><option value="">غير محدد</option><option value="SHORT">قصير</option><option value="MEDIUM">متوسط</option><option value="LONG">طويل</option></select></label>}{v.kind==='EXTENSIONS'&&<><label>لون الوصلات<input value={v.extensionColor??''} onChange={e=>change(v.id,'extensionColor',e.target.value||undefined)}/></label><label>طول الوصلات (سم)<input type="number" min="1" max="200" value={v.extensionLength??''} onChange={e=>change(v.id,'extensionLength',e.target.value?Number(e.target.value):undefined)}/></label><label>عدد الوصلات<input type="number" min="1" max="1000" value={v.extensionQuantity??''} onChange={e=>change(v.id,'extensionQuantity',e.target.value?Number(e.target.value):undefined)}/></label></>}<button type="button" onClick={()=>onChange({...value,variants:variants.filter(x=>x.id!==v.id)})}>إزالة خيار السعر</button></fieldset>)}<button type="button" onClick={()=>onChange({...value,variants:[...variants,{id:crypto.randomUUID(),name:'',price:0}]})}>إضافة خيار سعر</button></details>;
}
