'use client';
import {useEffect,useState} from 'react';
import {bodyRegions,regionLabels,quoteService,type Selection,type ServiceConfiguration} from '@/lib/service-selection';
import {ServicePriceOptions,ServicePriceEditor} from './ServicePriceOptions';
import {HairDetails,SkinFace} from './TreatmentDetails';
import {salonDayRange} from '@/lib/business-time';
import TreatmentBody from './TreatmentBody';
import {label} from '@/lib/crm-config';
const money=(n:unknown)=>`${Number(n).toFixed(2)} ₪`;
const empty:ServiceConfiguration={areas:[],offers:[]};
export function ServiceSkills({value,onChange}:{value:string[];onChange:(v:string[])=>void}){
 const [rows,setRows]=useState<Service[]>([]);const [error,setError]=useState('');
 useEffect(()=>{fetch('/api/crm/service-options').then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);setRows(d.rows??[]);}).catch(e=>setError(e.message));},[]);
 return <div>{error&&<p role="alert">{error}</p>}{rows.map(s=><label className="laser-area" key={s.id}><input type="checkbox" checked={value.includes(s.id)} onChange={e=>onChange(e.target.checked?[...value,s.id]:value.filter(id=>id!==s.id))}/>{s.name}</label>)}<small>تُعرض للعميلات المواعيد مع موظفة مؤهلة فقط.</small></div>;
}
type Service={id:string;name:string;department:string;price:unknown;imageUrl?:string;configuration?:ServiceConfiguration};
export function ServiceCards({rows,onSelect}:{rows:any[];onSelect:(s:Service)=>void}){
 const [category,setCategory]=useState('');
 return <div><div className="service-category-tabs" aria-label="تصنيف الخدمات">{[...new Set(rows.map(s=>s.department))].map(d=><button key={d} type="button" className={category===d?'active':''} onClick={()=>setCategory(d)}>{label(d)}</button>)}</div>{[...new Set(rows.map(s=>s.department))].filter(d=>category===d).map(dept=><section key={dept}><h3>{label(dept)}</h3><div className="service-cards">{rows.filter(s=>s.department===dept).map(s=><button type="button" className="service-card" key={s.id} onClick={()=>onSelect(s)}>{s.imageUrl?<img src={s.imageUrl} alt=""/>:<span aria-hidden="true">✦</span>}<strong>{s.name}</strong><span>{money(s.price)}</span><small>{s.durationMinutes>0?`${s.durationMinutes} دقيقة`:'المدة لم تحدد بعد'}</small></button>)}</div></section>)}</div>;
}
export function ServiceConfigurationEditor({value,onChange}:{value:ServiceConfiguration;onChange:(v:ServiceConfiguration)=>void}){
 const v={...empty,...value};
 return <div className="service-config"><ServicePriceEditor value={v} onChange={onChange}/><p>لخدمة الليزر: أضيفي المناطق والأسعار المعتمدة. رمز الجهاز أو الغرفة نفسه يمنع حجزه لخدمتين متزامنتين.</p>{v.areas.map((a,i)=><div className="service-config-row" key={a.id}><input aria-label="اسم المنطقة" placeholder="اسم المنطقة" value={a.name} onChange={e=>onChange({...v,areas:v.areas.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><select aria-label="موضع المنطقة في الرسم" value={a.region} onChange={e=>onChange({...v,areas:v.areas.map((x,j)=>j===i?{...x,region:e.target.value as typeof a.region}:x)})}>{bodyRegions.map(r=><option key={r} value={r}>{regionLabels[r]}</option>)}</select><select aria-label="النوع المتاح للمنطقة" value={a.audience??'ALL'} onChange={e=>onChange({...v,areas:v.areas.map((x,j)=>j===i?{...x,audience:e.target.value as 'ALL'|'FEMALE'|'MALE'}:x)})}><option value="ALL">للجميع</option><option value="FEMALE">أنثى</option><option value="MALE">ذكر</option></select><details><summary>المناطق المشمولة بالسعر</summary>{bodyRegions.map(r=><label key={r}><input type="checkbox" checked={(a.coverage??[a.region]).includes(r)} onChange={e=>{const coverage=e.target.checked?[...new Set([...(a.coverage??[a.region]),r])]:(a.coverage??[a.region]).filter(x=>x!==r);onChange({...v,areas:v.areas.map((x,j)=>j===i?{...x,coverage:coverage.length?coverage:undefined}:x)});}}/>{regionLabels[r]}</label>)}</details><input aria-label="سعر المنطقة" type="number" min="0" step="0.01" value={a.price} onChange={e=>onChange({...v,areas:v.areas.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x)})}/><button type="button" onClick={()=>{if(v.offers.some(o=>o.areaIds.includes(a.id))){window.alert('أزيلي المنطقة من العرض أولًا');return;}onChange({...v,areas:v.areas.filter(x=>x.id!==a.id)});}}>إزالة المنطقة</button></div>)}<button type="button" onClick={()=>onChange({...v,areas:[...v.areas,{id:crypto.randomUUID(),name:'',region:'FACE',price:0}]})}>إضافة منطقة</button>
 <h4>عروض اختيارية</h4>{v.offers.map((o,i)=><fieldset key={o.id}><legend>العرض {i+1}</legend><input aria-label="اسم العرض" placeholder="اسم العرض" value={o.name} onChange={e=>onChange({...v,offers:v.offers.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><input aria-label="سعر العرض" type="number" min="0" step="0.01" value={o.price} onChange={e=>onChange({...v,offers:v.offers.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x)})}/><div className="crm-inline">{v.areas.map(a=><label key={a.id}><input type="checkbox" checked={o.areaIds.includes(a.id)} onChange={e=>onChange({...v,offers:v.offers.map((x,j)=>j===i?{...x,areaIds:e.target.checked?[...x.areaIds,a.id]:x.areaIds.filter(id=>id!==a.id)}:x)})}/>{a.name}</label>)}</div><label>عدد جلسات الباقة<input type="number" min="1" max="100" value={o.sessionsTotal??1} onChange={e=>onChange({...v,offers:v.offers.map((x,j)=>j===i?{...x,sessionsTotal:Number(e.target.value)}:x)})}/></label><label>ينتهي بنهاية يوم (توقيت القدس)<input type="date" value={o.endsAt?.slice(0,10)??''} onChange={e=>onChange({...v,offers:v.offers.map((x,j)=>j===i?{...x,endsAt:e.target.value?new Date(+salonDayRange(new Date(`${e.target.value}T12:00:00Z`)).end-1).toISOString():undefined}:x)})}/></label><button type="button" onClick={()=>onChange({...v,offers:v.offers.filter(x=>x.id!==o.id)})}>إزالة العرض</button></fieldset>)}<button type="button" disabled={!v.areas.length} onClick={()=>onChange({...v,offers:[...v.offers,{id:crypto.randomUUID(),name:'',areaIds:[],price:0}]})}>إضافة عرض</button></div>;
}
const shapes:Record<string,string>={FACE:'M80 15a17 17 0 1 0 0 34a17 17 0 1 0 0-34',UNDERARMS:'M49 65h16v27H49z M95 65h16v27H95z',ARMS:'M39 68h13v93H35z M108 68h13l4 93h-17z',ABDOMEN:'M62 92h36v41H62z',BACK:'M62 62h36v71H62z',BIKINI:'M60 137h40l-20 25z',LEGS:'M58 161h20v100H56z M82 161h20l2 100H82z'};
export function LaserSelection({service,value,onChange}:{service:Service;value:Selection;onChange:(v:Selection)=>void}){
 const original=service.configuration??empty,gender=value.gender??'FEMALE',c={...original,areas:original.areas.filter(a=>(a.audience===undefined||a.audience==='ALL'||a.audience===gender)&&(gender==='MALE'||(a.region!=='BEARD'&&!a.coverage?.includes('BEARD'))))},ids=value.areaIds??[];
 const toggle=(id:string)=>onChange({...value,offerId:undefined,areaIds:ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]});
 const selectRegion=(region:string)=>{const regionIds=c.areas.filter(a=>a.region===region).map(a=>a.id);if(!regionIds.length)return;const all=regionIds.every(id=>ids.includes(id));onChange({...value,offerId:undefined,areaIds:all?ids.filter(id=>!regionIds.includes(id)):[...new Set([...ids,...regionIds])]});};
 let quote:ReturnType<typeof quoteService>|undefined;let quoteError='';try{quote=quoteService(service,value);}catch(e){if(ids.length)quoteError=e instanceof Error?e.message:'تعذر حساب السعر';}
 const now=Date.now(),offers=c.offers.filter(o=>o.areaIds.length===ids.length&&o.areaIds.every(id=>ids.includes(id))&&(!o.startsAt||+new Date(o.startsAt)<=now)&&(!o.endsAt||+new Date(o.endsAt)>=now));
 if(!original.areas.length)return <p>لم تُضف أسعار مناطق الليزر بعد. على الإدارة إعداد المناطق قبل الحجز.</p>;
 return <div className="laser-selection"><div className="laser-bodies"><div className="service-category-tabs" aria-label="نوع عميل الليزر">{(['FEMALE','MALE'] as const).map(g=><button type="button" key={g} aria-pressed={gender===g} className={gender===g?'active':''} onClick={()=>{if(ids.length&&!window.confirm('تغيير نوع العميل يمسح المناطق والعرض المحددين. هل تريدين المتابعة؟'))return;onChange({...value,gender:g,areaIds:[],offerId:undefined});}}>{g==='FEMALE'?'أنثى':'ذكر'}</button>)}</div><TreatmentBody gender={gender} available={[...new Set(c.areas.map(a=>a.region))]} selected={[...new Set(c.areas.filter(a=>ids.includes(a.id)).map(a=>a.region))]} onToggle={selectRegion}/></div><div>{c.areas.map(a=><label className="laser-area" key={a.id}><input type="checkbox" checked={ids.includes(a.id)} onChange={()=>toggle(a.id)}/><span>{a.name}</span><strong>{money(a.price)}</strong></label>)}{ids.length>0&&<button type="button" onClick={()=>onChange({...value,areaIds:[],offerId:undefined})}>مسح الاختيارات</button>}{offers.length>0&&<fieldset><legend>عروض مناسبة — اختيارية</legend><label><input type="radio" name={`offer-${service.id}`} checked={!value.offerId} onChange={()=>onChange({...value,offerId:undefined})}/>بدون عرض</label>{offers.map(o=><label className="laser-offer" key={o.id}><input type="radio" name={`offer-${service.id}`} checked={value.offerId===o.id} onChange={()=>onChange({...value,offerId:o.id})}/><span>{o.name} · {o.areaIds.map(id=>c.areas.find(a=>a.id===id)?.name).join('، ')}<br/><s>{money(quote?.originalPrice??0)}</s> ← {money(o.price)}{o.endsAt&&<small> · ينتهي {new Date(o.endsAt).toLocaleDateString('ar',{timeZone:'Asia/Jerusalem'})}</small>}</span></label>)}</fieldset>}{quoteError&&<p role="alert">{quoteError}</p>}{quote&&<p role="status" className="service-total">{quote.areas.map(a=>a.name).join(' + ')}<br/>المجموع: <strong>{money(quote.finalPrice)}</strong></p>}</div></div>;
}
export function ServiceDetails({serviceId,value,onChange}:{serviceId:string;value:Selection;onChange:(v:Selection)=>void}){
 const [service,setService]=useState<Service|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;setService(null);if(!serviceId)return;fetch('/api/crm/service-options?id='+encodeURIComponent(serviceId)).then(r=>r.json()).then(d=>{if(active){const s=d.rows?.find((s:Service)=>s.id===serviceId);setService(s??null);setError(s?'':'تعذر تحميل الخدمة');}}).catch(()=>{if(active)setError('تعذر تحميل تفاصيل الخدمة');});return()=>{active=false;};},[serviceId]);
 if(error)return <p role="alert">{error}</p>;if(!service)return <p>اختاري الخدمة لعرض تفاصيلها.</p>;
 return <ServiceDetailsFields service={service} value={value??{}} onChange={onChange}/>;
}
export function ServiceDetailsFields({service,value,onChange}:{service:Service;value:Selection;onChange:(v:Selection)=>void}){
 if(service.department==='LASER')return <LaserSelection service={service} value={value} onChange={onChange}/>;
 return <div className="service-details"><ServicePriceOptions configuration={service.configuration} value={value} onChange={onChange}/>{service.department==='HAIR'?<><label>نوع خدمة الشعر<select value={value.kind??''} onChange={e=>onChange({kind:e.target.value,notes:value.notes})}><option value="">اختاري النوع</option>{[['CUT','قص'],['COLOR','صبغة'],['TREATMENT','علاج'],['KERATIN','كيراتين'],['EXTENSIONS','وصلات']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{value.kind&&<label>طول الشعر<select value={value.hairLength??''} onChange={e=>onChange({...value,hairLength:e.target.value as Selection['hairLength']||undefined})}><option value="">اختاري الطول</option><option value="SHORT">قصير</option><option value="MEDIUM">متوسط</option><option value="LONG">طويل</option></select></label>}{value.kind==='EXTENSIONS'&&<><label>لون الوصلات<input value={value.extensionColor??''} onChange={e=>onChange({...value,extensionColor:e.target.value})}/></label><label>طول الوصلات (سم)<input type="number" min="1" max="200" value={value.extensionLength??''} onChange={e=>onChange({...value,extensionLength:e.target.value?Number(e.target.value):undefined})}/></label><label>عدد الوصلات<input type="number" min="1" max="1000" value={value.extensionQuantity??''} onChange={e=>onChange({...value,extensionQuantity:e.target.value?Number(e.target.value):undefined})}/></label></>}{value.kind==='COLOR'&&<HairDetails value={value} onChange={onChange}/>}</>:<label>{service.department==='SKIN'?'نوع جلسة البشرة':service.department==='MASSAGE'?'نوع المساج':'تفاصيل الخدمة'}<input value={value.kind??''} onChange={e=>onChange({...value,kind:e.target.value})}/></label>}{service.department==='SKIN'&&<SkinFace value={value} onChange={onChange}/>}{service.department==='SKIN'&&<div className="crm-inline">{([['CLEAN','تنظيف'],['PEEL','تقشير'],['STEAM','بخار'],['MASK','قناع ترطيب']] as const).map(([v,l])=><label key={v}><input type="checkbox" checked={value.steps?.includes(v)??false} onChange={e=>onChange({...value,steps:e.target.checked?[...(value.steps??[]),v]:value.steps?.filter(x=>x!==v)})}/>{l}</label>)}</div>}<label>ملاحظات اختيارية<textarea value={value.notes??''} onChange={e=>onChange({...value,notes:e.target.value})}/></label></div>;
}
