'use client';
import type {Selection} from '@/lib/service-selection';
const colors=[['أسود','#201a1b'],['بني داكن','#493028'],['بني متوسط','#785341'],['بني فاتح','#a77852'],['أشقر','#c6a37a'],['أشقر فاتح','#e3d3be']];
function Swatches({value,onChange,label}:{value?:string;onChange:(v:string)=>void;label:string}){return <div><p>{label}</p><div className="hair-swatches">{colors.map(([name,color])=><button type="button" key={name} style={{background:color}} aria-label={`${label}: ${name}`} aria-pressed={value===name} onClick={()=>onChange(name)}/>)}</div><p>{value??'لم يحدد'}</p></div>;}
function Levels({value,onChange,label}:{value?:number;onChange:(v:number)=>void;label:string}){return <div><p>{label}</p><div className="hair-levels">{Array.from({length:10},(_,i)=>i+1).map(n=><button type="button" key={n} aria-label={`${label} ${n}`} aria-pressed={value===n} onClick={()=>onChange(n)}>{n}</button>)}</div></div>;}
export function HairDetails({value,onChange}:{value:Selection;onChange:(v:Selection)=>void}){
 const set=(k:keyof Selection,v:any)=>onChange({...value,[k]:v});
 return <div className="treatment-details-grid"><section><h4>حالة الشعر الحالية</h4><Swatches value={value.currentColor} onChange={v=>set('currentColor',v)} label="لون الشعر الحالي"/><Levels value={value.currentLevel} onChange={v=>set('currentLevel',v)} label="مستوى اللون الحالي"/><label>طبيعة الشعر<select value={value.texture??''} onChange={e=>set('texture',e.target.value||undefined)}><option value="">اختياري</option><option value="SOFT">ناعم</option><option value="MEDIUM">متوسط</option><option value="COARSE">خشن</option></select></label><label>كثافة الشعر<select value={value.density??''} onChange={e=>set('density',e.target.value||undefined)}><option value="">اختياري</option><option value="LIGHT">خفيفة</option><option value="MEDIUM">متوسطة</option><option value="THICK">كثيفة</option></select></label></section><section><h4>اللون المطلوب والنتيجة</h4><Swatches value={value.color} onChange={v=>set('color',v)} label="اللون المطلوب"/><label>اللون<input value={value.color??''} onChange={e=>set('color',e.target.value)}/></label><label>الدرجة<input value={value.shade??''} onChange={e=>set('shade',e.target.value)}/></label><Levels value={value.targetLevel} onChange={v=>set('targetLevel',v)} label="مستوى اللون المطلوب"/><Levels value={value.resultLevel} onChange={v=>set('resultLevel',v)} label="مستوى اللون الناتج"/></section><section><h4>تفاصيل الجلسة والمنتجات المستخدمة</h4><label>المنتجات المستخدمة<input value={value.products??''} onChange={e=>set('products',e.target.value)}/></label><label>الصيغة والتركيبة<textarea value={value.formula??''} onChange={e=>set('formula',e.target.value)}/></label></section><section><h4>النتيجة بعد الجلسة</h4><textarea aria-label="نتيجة الصبغة" value={value.result??''} onChange={e=>set('result',e.target.value)}/></section></div>;
}
export function SkinFace({value,onChange}:{value:Selection;onChange:(v:Selection)=>void}){
 const areas=value.faceAreas??[];const names:Record<string,string>={FOREHEAD:'الجبهة',CHEEKS:'الخدان',NOSE:'الأنف',CHIN:'الذقن'};
 const toggle=(key:any)=>onChange({...value,faceAreas:areas.includes(key)?areas.filter(a=>a!==key):[...areas,key]});
 const paths:Record<string,string>={FOREHEAD:'M57 73Q100 37 143 73L137 92Q100 82 63 92Z',CHEEKS:'M49 120Q67 112 80 131L70 153Q48 153 49 120 M151 120Q133 112 120 131L130 153Q152 153 151 120',NOSE:'M96 112h8l9 35q-13 8-26 0Z',CHIN:'M76 179q24 15 48 0l-5 18q-19 16-38 0Z'};
 return <section className="skin-face"><h4>مناطق الوجه</h4><p>حددي المنطقة من الرسم أو القائمة</p><svg viewBox="0 0 200 240" aria-label="مناطق جلسة البشرة"><path d="M42 106Q25 25 101 22Q176 23 158 108L140 195 102 223 62 193Z" fill="#eed2c6" stroke="#a5837c"/><path d="M43 105Q24 14 102 19Q178 20 158 105Q144 44 107 52Q73 72 43 105" fill="#78524a"/><ellipse cx="100" cy="19" rx="23" ry="16" fill="#78524a"/><path d="M60 110q13-8 25 0m30 0q13-8 25 0M83 171q17 9 34 0" fill="none" stroke="#784a42" strokeWidth="2"/>{Object.entries(paths).map(([k,d])=><path key={k} d={d} tabIndex={0} role="button" aria-label={names[k]} aria-pressed={areas.includes(k as any)} onClick={()=>toggle(k)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle(k);}}} fill={areas.includes(k as any)?'#f071b78c':'#ffffff44'} stroke="#bd74a2" strokeDasharray="3 2"/>)}</svg><div className="crm-inline">{Object.entries(names).map(([k,l])=><label key={k}><input type="checkbox" checked={areas.includes(k as any)} onChange={()=>toggle(k)}/>{l}</label>)}</div></section>;
}
