// Shared form metadata. Authorization is separately enforced by crm-access.ts.
export type CrmField = { key: string; label: string; type: string; required?: boolean; options?: string[]; source?: string; initial?: unknown };
export type CrmDefinition = { title: string; model: string; section: string; fields: CrmField[]; columns: string[]; immutable?: boolean };
const f = (key: string, label: string, type = 'text', required = false, extra: Partial<CrmField> = {}): CrmField => ({ key, label, type, required, ...extra });
const rel = (key: string, label: string, source: string, required = false) => f(key,label,'relation',required,{source});
const sel = (key: string,label: string,options: string[],initial?: string) => f(key,label,'select',true,{options,initial:initial??options[0]});
const n = (key: string,label: string,initial=0) => f(key,label,'number',false,{initial});
const d = (key: string,label: string,required=false) => f(key,label,'date',required);
const memo = (key: string,label: string) => f(key,label,'textarea');
const check = (key: string,label: string) => f(key,label,'checkbox',false,{initial:false});
const customer = () => rel('customerId','العميلة','customers',true);
const staff = () => rel('staffId','الموظفة','staff');
export const departments = ['SALON','COLLEGE','EVENT','PRODUCTS'];
export const roles = ['GOD','ADMIN','MANAGER','ACCOUNTANT','RECEPTIONIST','STAFF','SALES','COLLEGE','TRAINER','EVENT_MANAGER','INVENTORY','VIEWER'];
export const outcomes = ['NEW','CONTACTED','NO_ANSWER','INTERESTED','DETAILS_SENT','THINKING','PROMISED_PAYMENT','SCHEDULED','BOOKED','DEPOSIT','CLOSED','NOT_INTERESTED','FUTURE'];
export const studentStates = ['NEW','CONTACTED','WAITING_DOCUMENTS','FOLLOW_UP','INTERESTED','DETAILS_SENT','CONSULTATION','RESERVED','DEPOSIT','REGISTERED','STUDYING','FROZEN','WITHDRAWN','COMPLETED','AWAITING_CERTIFICATE','CERTIFIED'];
export const eventStages = ['NEW','CONTACTED','DETAILS_SENT','FOLLOW_UP','WAITING_REPLY','WAITING_PAYMENT','PACKAGE_SELECTED','DEPOSIT','INCOMPLETE','REGISTERED','ATTENDED','LOST'];
const currency = () => sel('currency','العملة',['ILS','AED','USD']);
const channel = () => sel('channel','وسيلة التواصل',['WHATSAPP','PHONE','INSTAGRAM','IN_PERSON','EMAIL']);
const def = (title:string,model:string,section:string,fields:CrmField[],columns:string[],immutable=false):CrmDefinition => ({title,model,section,fields,columns,immutable});
export const crm: Record<string,CrmDefinition> = {
 customers:def('العملاء','customer','customers',[
   f('name','الاسم الكامل','text',true),f('phone','الهاتف الدولي','tel',true),f('departments','الأقسام','multi',true,{options:departments,initial:['SALON']}),
   sel('source','مصدر العميل',['OTHER','AD','INSTAGRAM','REFERRAL','WHATSAPP','WALK_IN']),sel('relationshipStatus','الحالة',['NEW','INTERESTED','ACTIVE','FOLLOW_UP','INACTIVE','RETURNING']),rel('ownerId','الموظفة المسؤولة','team'),
   f('city','المدينة'),f('country','الدولة','text',false,{initial:'IL'}),f('email','البريد الإلكتروني','email'),f('interestedIn','الخدمة المطلوبة'),d('followUpAt','المتابعة القادمة'),memo('allergies','حساسية أو موانع'),memo('careInstructions','تعليمات العناية'),check('photoConsent','الموافقة على التصوير'),check('serviceConsent','الموافقة على الشروط'),memo('notes','ملاحظات')
 ],['name','phone','departments','relationshipStatus','ownerId','followUpAt']),
 tasks:def('المتابعات والمهام','task','tasks',[customer(),rel('ownerId','الموظفة المسؤولة','team',true),d('contactedAt','تاريخ التواصل'),channel(),f('reason','سبب التواصل','text',true),memo('summary','ملخص المحادثة'),sel('outcome','النتيجة',outcomes),f('nextAction','الخطوة القادمة'),d('dueAt','المتابعة القادمة'),sel('priority','الأولوية',['NORMAL','MEDIUM','HIGH']),d('completedAt','تاريخ إتمام المهمة')],['customerId','reason','ownerId','outcome','nextAction','dueAt','priority']),
 appointments:def('تقويم المواعيد','appointment','salon',[customer(),rel('serviceId','الخدمة','services',true),staff(),d('startsAt','الموعد',true),n('durationMinutes','المدة بالدقائق',60),n('price','سعر الخدمة'),sel('status','الحضور',['PENDING_REPLY','CONFIRMED','SCHEDULED','COMPLETED','NO_SHOW','CANCELLED'],'PENDING_REPLY'),memo('sessionNotes','الخدمة المنفذة وملاحظات الجلسة'),memo('notes','ملاحظات الحجز'),rel('invoiceId','فاتورة الخدمة','invoices'),d('nextFollowUpAt','موعد العودة أو المتابعة')],['startsAt','customerId','serviceId','staffId','status']),
 services:def('الخدمات والأسعار','service','salon',[f('name','الخدمة','text',true),n('price','السعر'),n('durationMinutes','المدة بالدقائق',60),sel('department','القسم',['SALON','HAIR','LASER']),f('active','فعالة','checkbox',false,{initial:true})],['name','department','price','durationMinutes','active']),
 laserPlans:def('الباقات والليزر','laserPlan','salon',[customer(),sel('category','نوع الباقة',['LASER','HAIR','SALON']),f('area','مناطق العلاج / اسم الباقة','text',true),n('price','سعر الباقة'),n('sessionsTotal','عدد الجلسات',1),d('startedAt','تاريخ البداية'),d('followUpAt','الجلسة القادمة'),memo('consentNotes','شروط الباقة والموافقة')],['customerId','area','price','sessionsTotal','sessionsUsed','followUpAt']),
 laserSessions:def('جلسات الليزر','laserSession','salon',[rel('planId','الباقة','laserPlans',true),staff(),d('performedAt','تاريخ الجلسة'),f('device','الجهاز'),f('settings','الإعدادات'),memo('skinHairNotes','ملاحظات الشعر والجلد'),memo('contraindications','الموانع والحساسية'),memo('notes','ملاحظات الجلسة'),d('nextSessionAt','الجلسة القادمة')],['planId','staffId','performedAt','device','nextSessionAt']),
 hairSessions:def('خدمات الشعر','hairSession','salon',[customer(),staff(),f('service','نوع الخدمة','text',true),memo('diagnosis','تشخيص الشعر'),memo('materials','المواد المستخدمة'),memo('quantities','كميات المواد'),memo('result','النتيجة'),memo('homeCare','العناية المنزلية'),d('performedAt','تاريخ الخدمة'),d('renewalAt','التجديد المتوقع')],['customerId','service','staffId','performedAt','renewalAt']),
 students:def('مهتمات وطالبات','student','college',[customer(),sel('status','الحالة',studentStates),f('collegeService','خدمة الكلية','select',false,{options:['CONSULTATION','REGISTRATION','ADMISSION','PAPERWORK','FOLLOW_UP'],initial:'CONSULTATION'}),f('requiredDocuments','المستندات المطلوبة','tags'),f('receivedDocuments','المستندات المستلمة','tags'),f('interestedCourse','الكورس المطلوب'),sel('interest','درجة الاهتمام',['MEDIUM','HIGH','LOW']),f('objection','الاعتراض'),n('quotedPrice','السعر المعروض'),n('offeredDiscount','الخصم المعروض'),f('notRegisteredReason','سبب عدم التسجيل'),d('followUpAt','المتابعة القادمة'),memo('notes','ملاحظات')],['customerId','status','collegeService','interestedCourse','missingDocuments','followUpAt']),
 collegeCourses:def('الكورسات والمجموعات','collegeCourse','college',[f('title','الكورس','text',true),f('groupName','المجموعة'),memo('description','الوصف'),n('fee','السعر'),n('cost','التكلفة'),rel('trainerId','المدربة','team'),rel('coordinatorId','منسقة المجموعة','team'),d('startsAt','تاريخ البداية'),d('endsAt','تاريخ النهاية'),n('hours','عدد الساعات'),n('capacity','السعة',20),memo('includedKit','الأدوات المشمولة'),sel('status','الحالة',['UPCOMING','OPEN','RUNNING','COMPLETED']),f('active','فعال','checkbox',false,{initial:true})],['title','groupName','trainerId','startsAt','capacity','enrolledCount','remainingSeats','status']),
 enrollments:def('التسجيلات','studentEnrollment','college',[rel('studentId','الطالبة','students',true),rel('courseId','الكورس والمجموعة','collegeCourses',true),n('fee','المبلغ النهائي'),sel('status','حالة الطالبة',studentStates,'REGISTERED'),d('enrolledAt','تاريخ التسجيل'),sel('certificateStatus','الشهادة',['PENDING','READY','DELIVERED','NONE']),d('kitReceivedAt','استلام الأدوات'),memo('trainerNotes','ملاحظات المدربة'),memo('notes','ملاحظات')],['studentId','courseId','status','certificateStatus','invoiceId']),
 courseSessions:def('جدول اللقاءات','courseSession','college',[rel('courseId','الكورس','collegeCourses',true),f('title','عنوان اللقاء','text',true),d('startsAt','البداية',true),d('endsAt','النهاية',true)],['courseId','title','startsAt','endsAt']),
 attendance:def('الحضور والتقييم','attendance','college',[rel('sessionId','اللقاء','courseSessions',true),rel('enrollmentId','التسجيل','enrollments',true),sel('status','الحضور',['PRESENT','ABSENT','EXCUSED']),n('grade','التقييم من 100'),memo('notes','ملاحظات المدربة')],['sessionId','enrollmentId','status','grade','notes']),
 events:def('الإيفنتات','event','events',[f('name','اسم الإيفنت','text',true),f('location','المكان'),d('startsAt','التاريخ'),rel('managerId','المسؤولة','team'),currency(),n('depositRequired','العربون المطلوب للتسجيل'),n('capacity','حد المقاعد (0 دون حد)'),memo('notes','التفاصيل')],['name','location','startsAt','managerId','capacity','reservedSeats','remainingSeats','currency']),
 eventPackages:def('باقات الإيفنت','eventPackage','events',[rel('eventId','الإيفنت','events',true),f('name','الباقة','text',true),n('price','السعر'),memo('description','التفاصيل'),f('active','فعالة','checkbox',false,{initial:true})],['eventId','name','price','description']),
 eventLeads:def('المهتمات والمشتركات','eventLead','events',[customer(),rel('eventId','الإيفنت','events',true),rel('packageId','الباقة','eventPackages'),sel('stage','مرحلة التسجيل',eventStages),n('partySize','عدد الأشخاص والمقاعد',1),sel('region','المنطقة',['LOCAL','DUBAI','OTHER']),n('originalPrice','السعر الأصلي'),n('discount','الخصم'),f('discountReason','سبب الخصم'),currency(),d('nextPaymentAt','الدفعة القادمة'),d('followUpAt','المتابعة القادمة'),check('vip','VIP'),check('flight','يشمل طيران'),f('flightDetails','الطيران'),f('transferDetails','النقل'),check('hotel','يشمل فندق'),f('hotelName','الفندق'),f('roomType','نوع الغرفة'),f('companion','المرافقة'),check('certificate','شهادة'),sel('certificateStatus','حالة الشهادة',['PENDING','READY','DELIVERED','NONE']),check('attended','حضرت'),memo('specialNeeds','احتياجات خاصة'),memo('notes','ملاحظات')],['customerId','eventId','packageId','stage','vip','agreedAmount','paidAmount','currency','nextPaymentAt']),
 products:def('المنتجات','product','inventory',[f('name','المنتج','text',true),f('imageUrl','رابط الصورة المحلي'),f('category','التصنيف','text',true),f('supplier','المورد'),n('purchasePrice','سعر الشراء'),n('salePrice','سعر البيع'),currency(),n('minimum','الحد الأدنى'),f('storageLocation','مكان التخزين'),sel('purpose','الاستخدام',['SALE','KIT','SALON'])],['imageUrl','name','category','supplier','salePrice','stock','minimum','purpose']),
 stockMovements:def('حركات المخزون','stockMovement','inventory',[rel('productId','المنتج','products',true),rel('customerId','العميلة / الطالبة','customers'),sel('kind','نوع الحركة',['PURCHASE','SALE','SALON_USE','KIT','RETURN','DAMAGE','ADJUSTMENT']),n('quantity','الكمية (التعديل يقبل السالب)',1),f('batch','رقم التشغيلة','text',true),d('expiresAt','تاريخ الانتهاء'),f('reason','السبب','text',true)],['productId','kind','quantity','batch','customerId','reason','createdAt'],true),
 supplierOrders:def('طلبات الموردين','supplierOrder','inventory',[rel('productId','المنتج','products',true),f('supplier','المورد','text',true),n('quantity','الكمية',1),d('expectedAt','الوصول المتوقع',true),sel('status','الحالة',['PENDING','RECEIVED','CANCELLED']),memo('notes','ملاحظات')],['productId','supplier','quantity','expectedAt','status']),
 invoices:def('الفواتير','invoice','finance',[customer(),f('description','الوصف','text',true),n('originalAmount','المبلغ الأصلي'),n('discount','الخصم'),f('discountReason','سبب الخصم'),currency(),sel('department','القسم',departments),d('dueAt','موعد القسط القادم'),rel('serviceId','الخدمة','services'),n('initialPayment','الدفعة الأولى'),f('paymentMethod','طريقة الدفع','select',false,{options:['CASH','CARD','BANK','OTHER'],initial:'CASH'}),memo('paymentNote','ملاحظة الدفعة'),memo('notes','ملاحظة الفاتورة')],['customerId','description','amount','paidAmount','balance','currency','status','dueAt']),
 payments:def('حركات الدفعات','payment','finance',[rel('invoiceId','الفاتورة','invoices',true),n('amount','المبلغ'),sel('method','طريقة الدفع',['CASH','CARD','BANK','OTHER']),sel('kind','نوع الحركة',['PAYMENT','REFUND']),d('paidAt','تاريخ الدفعة'),rel('receiptDocumentId','صورة الإيصال','documents'),memo('notes','ملاحظات / سبب الاسترداد')],['invoiceId','amount','kind','method','receivedById','paidAt','voidedAt'],true),
 expenses:def('المصروفات','expense','finance',[f('payee','المستفيد','text',true),f('category','التصنيف','text',true),f('description','الوصف','text',true),n('amount','المبلغ'),d('dueAt','الاستحقاق',true),d('paidAt','تاريخ الدفع')],['payee','description','amount','dueAt','status']),
 staff:def('الموظفون','staff','staff',[f('name','الاسم','text',true),f('phone','الهاتف','tel'),f('email','البريد','email'),f('title','الوظيفة'),sel('department','القسم',departments),f('services','الخدمات المقدمة','tags'),f('schedule','الأيام والساعات','schedule'),n('commissionRate','العمولة %'),f('active','فعال','checkbox',false,{initial:true})],['name','title','department','phone','active']),
 leaves:def('الإجازات','employeeLeave','staff',[staff(),d('startsAt','من',true),d('endsAt','إلى',true),f('reason','السبب','text',true),sel('status','الحالة',['PENDING','APPROVED','REJECTED'])],['staffId','startsAt','endsAt','reason','status']),
 users:def('المستخدمون والصلاحيات','user','settings',[f('name','الاسم','text',true),f('username','اسم المستخدم','text',true),f('email','البريد','email'),f('password','كلمة المرور','password'),sel('role','الدور',roles,'STAFF'),staff(),f('active','فعال','checkbox',false,{initial:true})],['name','username','role','staffId','active']),
 workingHours:def('ساعات العمل','workingHour','settings',[n('dayOfWeek','اليوم: الأحد 0 — السبت 6'),f('openTime','الفتح HH:mm','text',true),f('closeTime','الإغلاق HH:mm','text',true),f('active','فعال','checkbox',false,{initial:true})],['dayOfWeek','openTime','closeTime','active']),
 templates:def('قوالب واتساب','messageTemplate','settings',[f('name','اسم القالب','text',true),memo('body','النص: استخدمي {name} للاسم'),sel('department','القسم',departments),f('active','فعال','checkbox',false,{initial:true})],['name','department','body']),
 notes:def('الملاحظات','customerNote','customers',[customer(),f('department','القسم','select',false,{options:[...departments,'FINANCE']}),f('body','الملاحظة','textarea',true)],['department','body','authorName','updatedAt']),
 documents:def('الصور والمستندات','customerDocument','customers',[rel('invoiceId','الفاتورة','invoices')],['filename','category','invoiceId','createdAt']),
 audit:def('سجل المراقبة','auditLog','settings',[],['actorName','action','entity','entityId','details','createdAt']),
 team:def('الفريق','user','staff',[],['name','role'])
};
export const sections = [
 ['overview','نظرة عامة','◈'],['customers','العملاء','♧'],['tasks','المتابعات والمهام','✓'],['salon','الصالون','✦'],['college','الكلية','◇'],['events','الإيفنتات','✧'],['inventory','المنتجات والمخزون','▦'],['finance','الدفعات والفواتير','₪'],['staff','الموظفون','♙'],['reports','التقارير','▥'],['settings','الإعدادات والصلاحيات','⚙']
];
export const labels:Record<string,string> = {
 FINANCE:'مالية',WAITING_DOCUMENTS:'بانتظار الأوراق',WAITING_REPLY:'بانتظار الرد',WAITING_PAYMENT:'بانتظار الدفعة',PENDING_REPLY:'بانتظار الرد',CONFIRMED:'تم التأكيد',REGISTRATION:'التسجيل',ADMISSION:'القبول',PAPERWORK:'مساعدة الأوراق',reservedSeats:'المقاعد المحجوزة',SALON:'صالون',COLLEGE:'كلية',EVENT:'إيفنت',PRODUCTS:'منتجات',HAIR:'شعر',LASER:'ليزر',OTHER:'أخرى',AD:'إعلان',INSTAGRAM:'إنستغرام',REFERRAL:'توصية',WHATSAPP:'واتساب',WALK_IN:'حضوري',
 NEW:'جديدة',ACTIVE:'فعالة',INACTIVE:'غير فعالة',RETURNING:'عائدة',FOLLOW_UP:'متابعة',CONTACTED:'تم التواصل',NO_ANSWER:'لم ترد',INTERESTED:'مهتمة',DETAILS_SENT:'أُرسلت التفاصيل',THINKING:'تحتاج وقتًا للتفكير',PROMISED_PAYMENT:'وعدت بالدفع',SCHEDULED:'موعد قادم',BOOKED:'حجزت',DEPOSIT:'دفعت عربون',CLOSED:'أُغلقت الصفقة',NOT_INTERESTED:'غير مهتمة',FUTURE:'متابعة مستقبلية',NORMAL:'عادية',MEDIUM:'متوسطة',HIGH:'عالية',LOW:'منخفضة',PHONE:'اتصال',IN_PERSON:'حضوري',EMAIL:'بريد',
 COMPLETED:'مكتمل',NO_SHOW:'لم تحضر',CANCELLED:'ملغي',CONSULTATION:'استشارة',RESERVED:'حجزت مكانًا',REGISTERED:'تسجيل مكتمل',STUDYING:'بدأت الدراسة',FROZEN:'مجمدة',WITHDRAWN:'انسحبت',AWAITING_CERTIFICATE:'بانتظار الشهادة',CERTIFIED:'استلمت الشهادة',PENDING:'بانتظار',READY:'جاهزة',DELIVERED:'تم التسليم',NONE:'بدون',UPCOMING:'قادم',OPEN:'مفتوح',RUNNING:'جارٍ',PRESENT:'حضرت',ABSENT:'غائبة',EXCUSED:'بعذر',PACKAGE_SELECTED:'اختارت باقة',INCOMPLETE:'تسجيل ناقص',ATTENDED:'حضرت',LOST:'غير مهتمة',LOCAL:'من البلاد',DUBAI:'الإمارات',
 SALE:'بيع',KIT:'تسليم Kit',PURCHASE:'شراء من المورد',SALON_USE:'استخدام الصالون',RETURN:'مرتجع',DAMAGE:'تالف',ADJUSTMENT:'تعديل مع السبب',RECEIVED:'وصل',CASH:'نقد',CARD:'بطاقة',BANK:'تحويل',PAYMENT:'دفعة',REFUND:'استرداد',UNPAID:'غير مدفوع',PARTIAL:'مدفوع جزئيًا',PAID:'مدفوع كاملًا',VOID:'ملغي',DUE:'مستحق',APPROVED:'مقبول',REJECTED:'مرفوض',
 GOD:'المالكة — صلاحية كاملة',ADMIN:'إدارة كاملة',MANAGER:'المديرة',ACCOUNTANT:'المحاسبة',RECEPTIONIST:'موظفة استقبال',STAFF:'موظفة صالون',SALES:'مندوبة مبيعات',TRAINER:'المدربة',EVENT_MANAGER:'مسؤولة الإيفنت',INVENTORY:'مسؤولة المخزون',VIEWER:'مشاهدة',
 sessionsUsed:'الجلسات المنفذة',enrolledCount:'المسجلات',remainingSeats:'المقاعد المتبقية',stock:'الكمية',balance:'المتبقي',paidAmount:'المدفوع',amount:'المبلغ النهائي',agreedAmount:'السعر النهائي',createdAt:'تاريخ الإضافة',updatedAt:'آخر تعديل',voidedAt:'تاريخ الإلغاء',receivedById:'استلمت بواسطة',authorName:'الموظفة',actorName:'الموظفة',action:'الإجراء',entity:'نوع السجل',entityId:'السجل',details:'التغيير',filename:'اسم الملف',category:'التصنيف',invoiceId:'الفاتورة',status:'الحالة',DOCUMENT:'مستند',BEFORE:'قبل',AFTER:'بعد',WORK:'عمل الطالبة',RECEIPT:'إيصال'
};
export function label(key:string) { return labels[key] ?? key; }
labels.LEADS='المهتمات';labels.REGISTRATIONS='المسجلات فعليًا';labels.missingDocuments='الأوراق الناقصة';labels.NEW_TODAY='الجديدات اليوم';
labels.margin='هامش الربح';
labels.ENROLLED='مسجلة';
labels.AWAITING_DETAILS='بانتظار التفاصيل';
